### ISSUE TITLE
出现以下问题怎么解

### ISSUE THREAD

**Issue by abcdxyzs** [abcfy2/getComic#24]
```python
Traceback (most recent call last):
  File "getComic-gui.py", line 195, in run
    imgList = getComic.getImgList(self.contentList[i]['url'])
  File "C:\Users\lenovo\Downloads\getComic-master\getComic-master\getComic.py", line 100, in getImgList
    nonce = re.findall(r'data-mpmvr="(.+?)"', chapter_page)[0]
IndexError: list index out of range
```

**Comment by abcfy2** [comment]
应该是腾讯动漫页面改版了，被和谐了
